"use client";
import {useState, useEffect} from "react";
import { usePathname } from "next/navigation"; // New hook
// import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/page";
import TopBar from "@/components/top-bar/page";
import LoadingScreen from "@/components/loadingscreen/page";
import { ProductProvider } from "@/context/productContext/productcontext";

const inter = Inter({subsets: ["latin"]});

// export const metadata: Metadata = {
//   title: "Okey Mart",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [loading, setLoading] = useState(true);
  const pathname = usePathname(); // Replaces useRouter()

  // Define pages where you want to hide TopBar and Footer
  const hiddenPages = ["/signin", "/signup", "/forgotten_password"];

  // Check if the current path matches any of the hidden pages
  const hideLayout = hiddenPages.includes(pathname);

  // Run this effect on the initial load
  useEffect(() => {
    const handleLoad = () => {
      setTimeout(() => {
        setLoading(false);
        // Enable scrolling once loading is done
        document.body.style.overflow = "auto";
      }, 3000); // Adjust delay as needed
    };

    // Disable scrolling while loading
    document.body.style.overflow = "hidden";

    if (document.readyState === "complete") {
      handleLoad();
    } else {
      window.addEventListener("load", handleLoad);
    }

    return () => {
      window.removeEventListener("load", handleLoad);
    };
  }, []);

  return (
    <ProductProvider>
      <html lang="en">
        <head>
          <meta charSet="UTF-8" />
        </head>
        <body>
          {loading && <LoadingScreen />}
          <div className={loading ? "hidden-load" : "fadeIn-load"}>
            <div className="page-container">
              {/* Conditionally render TopBar */}
              {!hideLayout && <TopBar />}
              <div className={`${inter.className} content`}>{children}</div>
            </div>
            {/* Conditionally render Footer */}
            {!hideLayout && <Footer />}
          </div>
        </body>
      </html>
    </ProductProvider>
  );
}
